sonar.projectKey=mayavi-team-fenghuat
sonar.projectName=mayavi-fork

sonar.sources=mayavi/modules
sonar.inclusions=mayavi/modules/**/*.py
sonar.exclusions=**/__pycache__/**,**/*.pyc

sonar.sourceEncoding=UTF-8
sonar.python.version=3.10
sonar.scm.disabled=true
